## Configuración del servidor
server:
  port: ${SERVER_PORT:8080}

## Configuración de la aplicación Spring Boot
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:search-microservice}
  config:
    import: optional:file:.env[.properties]

## Configuración del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}

## Configuración de Elasticsearch con Bonsai
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}

## Configuración de logging
logging:
  level:
    tracer: ${LOGGING_LEVEL_TRACER:TRACE}
